# Generated by Django 5.0 on 2023-12-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_alter_comision_carrera_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='url_img',
            field=models.CharField(max_length=500),
        ),
    ]
