# Generated by Django 4.2.7 on 2023-12-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0004_remove_comision_numero_comision_codigo_comision_cupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='cupo',
        ),
        migrations.AddField(
            model_name='comision',
            name='horario',
            field=models.CharField(default='', max_length=30),
        ),
    ]
