# Generated by Django 4.2.7 on 2023-12-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0005_remove_comision_cupo_comision_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(default='alumno@gmail.com', max_length=254),
        ),
    ]
