# Generated by Django 4.2.7 on 2023-12-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0007_suscripto_carrera_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='url_img',
            field=models.TextField(),
        ),
    ]
